//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_table
    {
        public int application_id { get; set; }
        public string job_description { get; set; }
        public string minimum_qualification { get; set; }
        public string preferred_qualification { get; set; }
        public string responsibility { get; set; }
        public Nullable<int> request_id { get; set; }
        public string application_status { get; set; }
        public string manager_name { get; set; }
        public string project_name { get; set; }
        public Nullable<int> period_month { get; set; }
        public Nullable<int> noof_vacancies { get; set; }
        public string skill { get; set; }
        public string program_language { get; set; }
        public Nullable<int> experience_years { get; set; }
        public string designation { get; set; }
        public Nullable<System.DateTime> date_application { get; set; }
    
        public virtual request_table request_table { get; set; }
    }
}
